name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest, macos-14]
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4          
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup venv
      run: python -m venv .env
    - if: ${{ startsWith(matrix.runner, "windows") }}
      run: echo windows
    - if: ${{ !startsWith(matrix.runner, "windows") }}
      run: echo unix      
    # - name: Activate venv
    #   if: ${{ startsWith((matrix.runner, "windows" }}
    #   run: .env\Scripts\activate
    # - name: Activate venv
    #   if: ${{ !startsWith((matrix.runner, "windows" }}
    #   run: .env/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin
        maturin develop --release        
        pip install pytest
        pip install -r requirements.txt
    - name: Run tests
      run: |
        source .env/bin/activate
        pytest
